services:
  - type: web
    name: regexlab
    region: oregon
    env: docker
    dockerfilePath: Dockerfile
    dockerBuildContext: .
    buildCommand: >
      composer install --no-dev --prefer-dist --no-interaction &&
      npm ci --legacy-peer-deps &&
      npm run build &&
      php artisan optimize
    startCommand: apache2-foreground
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: "null"
      - key: DB_DATABASE
        value: "null"
      - key: APP_URL
        value: "https://regexlab.onrender.com"
    autoDeploy: true
    pullRequestPreviewsEnabled: false