services:
  - type: web
    name: expresiones
    region: oregon
    env: docker
    plan: free
    
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:zwUb5WuY54nCeCZOtqSlByHTals6V0URrVqhF+15LcU=
      - key: APP_URL
        value: "https://expresiones.onrender.com"
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: info
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: DB_CONNECTION
        value: sqlite
    
    healthCheckPath: /
    autoDeploy: true